# 配置文件加密
jasypt:
  encryptor:
    password: xcloud

server:
  port: 1003

spring:
  application:
    name: oauth-server
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 10000

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

# OAuth配置
xcloud:
  oauth:
    clientId: ENC(Kaq1/mCkIM/fkHWr4COfSA==)
    secret: ENC(swRBBeV4fGUpwnMz53o3UQ==)
    # 权限范围 可选项
    scope: xcloud

# Swagger界面内容配置
swagger:
  title: XCloud OAuthServer API接口文档
  description: XCloud OAuthServer Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com